import { render } from 'solid-js/web'
import '@material/web/button/filled-button.js'
import '@material/web/button/filled-tonal-button.js'
import '@material/web/button/outlined-button.js'
import '@material/web/button/text-button.js'
import '@material/web/chips/assist-chip.js'
import '@material/web/divider/divider.js'
import '@material/web/labs/card/filled-card.js'
import '@material/web/labs/card/outlined-card.js'
import '@material/web/labs/navigationbar/navigation-bar.js'
import '@material/web/labs/navigationtab/navigation-tab.js'
import '@material/web/list/list-item.js'
import '@material/web/list/list.js'
import '@material/web/progress/linear-progress.js'
import '@material/web/select/outlined-select.js'
import '@material/web/select/select-option.js'
import '@material/web/switch/switch.js'
import '@material/web/textfield/outlined-text-field.js'
import App from './App'
import './styles.css'

render(() => <App />, document.getElementById('app')!)
