rime-ice|雾凇拼音|iDvel/rime-ice|asset:full\.zip|0|schema
rime-frost|白霜拼音|gaboolic/rime-frost|asset:rime-frost-schemas\.zip|1|schema
oh-my-rime|oh-my-rime|Mintimate/oh-my-rime|archive|2|schema
moegirl|萌娘百科词库|outloudvi/mw2fcitx|asset-files:moegirl\.dict\.yaml$|3|dict
wanxiang|万象拼音|amzxyz/rime_wanxiang|asset:rime-wanxiang-base\.zip|5|schema
zhwiki|维基百科词库|felixonmars/fcitx5-pinyin-zhwiki|asset-files:^zhwiki-.*\.dict\.yaml$|10|dict
wanxiang-gram|万象语法模型|amzxyz/RIME-LMDG|asset-files:[Ll][Tt][Ss].*\.gram$@LTS|20|model
